/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  IsNumber,
  ValidateNested,
} from "class-validator";
import { RentalCreateNestedManyWithoutCarsInput } from "./RentalCreateNestedManyWithoutCarsInput";
import { Type } from "class-transformer";
import { ReviewCreateNestedManyWithoutCarsInput } from "./ReviewCreateNestedManyWithoutCarsInput";

@InputType()
class CarCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  model?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  year?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fuelType?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  pricePerDay?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => RentalCreateNestedManyWithoutCarsInput,
  })
  @ValidateNested()
  @Type(() => RentalCreateNestedManyWithoutCarsInput)
  @IsOptional()
  @Field(() => RentalCreateNestedManyWithoutCarsInput, {
    nullable: true,
  })
  rentals?: RentalCreateNestedManyWithoutCarsInput;

  @ApiProperty({
    required: false,
    type: () => ReviewCreateNestedManyWithoutCarsInput,
  })
  @ValidateNested()
  @Type(() => ReviewCreateNestedManyWithoutCarsInput)
  @IsOptional()
  @Field(() => ReviewCreateNestedManyWithoutCarsInput, {
    nullable: true,
  })
  reviews?: ReviewCreateNestedManyWithoutCarsInput;
}

export { CarCreateInput as CarCreateInput };
